api = "0.2"

[buildpack]
id = "fxtentacle/heroku-buildpack-multi"
version = "0.1"
name = "fxtentacle heroku buildpack multi"

[[stacks]]
id = "gitspacer-18"

[[stacks]]
id = "gitspacer-20"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"
